;;;; -*- encoding:utf-8 -*-
;;;; Fluxion - Database-backed session store
;;;;
;;;; Implements the session store protocol using fluxion.db for persistence.
;;;; Sessions are serialized to a configurable database table and can be
;;;; restored on server restart.

(defpackage #:fluxion.session.db
  (:use #:cl)
  (:local-nicknames (#:db #:fluxion.db)
                    (#:q #:fluxion.db.query))
  (:export
   #:db-session-store
   #:make-db-session-store
   #:session-store-backend
   #:session-store-collection))

(in-package #:fluxion.session.db)

;;; -------------------------------------------------------
;;; Database session store
;;; -------------------------------------------------------

(defclass db-session-store ()
  ((backend :initarg :backend
            :accessor session-store-backend
            :documentation "The fluxion.db backend used for session storage.")
   (collection :initarg :collection
               :accessor session-store-collection
               :initform "fluxion_sessions"
               :documentation "Name of the DB collection (table) for sessions."))
  (:documentation "Session store backed by a fluxion.db database.
Persists session metadata to a database table. Components and event
queues are not persisted (they are recreated at runtime)."))

(defun make-db-session-store (backend &key (collection "fluxion_sessions"))
  "Create a database-backed session store.
BACKEND is a connected fluxion.db backend instance."
  (make-instance 'db-session-store :backend backend :collection collection))

(defparameter *session-table-structure*
  '((sid :text)
    (created_at :integer)
    (last_accessed_at :integer)
    (csrf_token :text)
    (user_data :text)
    (user_roles :text))
  "Structure for the session storage table.
The _id column is auto-generated by fluxion.db but we use sid as the
actual session identifier since _id is an integer primary key.")

;;; -------------------------------------------------------
;;; Row conversion
;;; -------------------------------------------------------

(defun %row-to-session (row)
  "Convert a database row alist to a session instance."
  (let ((session (make-instance 'fluxion.server:session
                   :id (cdr (assoc "sid" row :test #'string=)))))
    (let ((created (cdr (assoc "created_at" row :test #'string=))))
      (when created
        (setf (fluxion.server:session-created-at session) created)))
    (let ((accessed (cdr (assoc "last_accessed_at" row :test #'string=))))
      (when accessed
        (setf (fluxion.server:session-last-accessed-at session) accessed)))
    (let ((csrf (cdr (assoc "csrf_token" row :test #'string=))))
      (when (and csrf (stringp csrf) (plusp (length csrf)))
        (setf (fluxion.server:session-csrf-token session) csrf)))
    (let ((user-str (cdr (assoc "user_data" row :test #'string=))))
      (when (and user-str (stringp user-str) (plusp (length user-str)))
        (handler-case
            (setf (fluxion.server:session-user session)
                  (read-from-string user-str))
          (error () nil))))
    (let ((roles-str (cdr (assoc "user_roles" row :test #'string=))))
      (when (and roles-str (stringp roles-str) (plusp (length roles-str)))
        (handler-case
            (setf (fluxion.server:session-user-roles session)
                  (read-from-string roles-str))
          (error () nil))))
    session))

;;; -------------------------------------------------------
;;; Store protocol implementation
;;; -------------------------------------------------------

(defmethod fluxion.server:store-setup ((store db-session-store))
  (let ((db:*backend* (session-store-backend store))
        (name (session-store-collection store)))
    (unless (db:collection-exists-p name)
      (db:create name *session-table-structure*))))

(defmethod fluxion.server:store-session ((store db-session-store) session)
  (let ((db:*backend* (session-store-backend store))
        (name (session-store-collection store))
        (sid (fluxion.server:session-id session)))
    ;; Upsert: delete then insert (portable across SQLite and PostgreSQL)
    (handler-case
        (db:remove name (q:compile-query `(:= sid ,sid)))
      (error () nil))
    (let ((user-str (when (fluxion.server:session-user session)
                      (prin1-to-string (fluxion.server:session-user session))))
          (roles-str (when (fluxion.server:session-user-roles session)
                       (prin1-to-string (fluxion.server:session-user-roles session)))))
      (db:insert name
                 `(("sid" . ,sid)
                   ("created_at" . ,(fluxion.server:session-created-at session))
                   ("last_accessed_at" . ,(fluxion.server:session-last-accessed-at session))
                   ("csrf_token" . ,(fluxion.server:session-csrf-token session))
                   ("user_data" . ,(or user-str ""))
                   ("user_roles" . ,(or roles-str "")))))))

(defmethod fluxion.server:load-session ((store db-session-store) session-id)
  (let ((db:*backend* (session-store-backend store))
        (name (session-store-collection store)))
    (let ((row (db:select-one name (q:compile-query `(:= sid ,session-id)))))
      (when row
        (%row-to-session row)))))

(defmethod fluxion.server:delete-session ((store db-session-store) session-id)
  (let ((db:*backend* (session-store-backend store))
        (name (session-store-collection store)))
    (handler-case
        (db:remove name (q:compile-query `(:= sid ,session-id)))
      (error () nil))))

(defmethod fluxion.server:load-all-sessions ((store db-session-store))
  (let ((db:*backend* (session-store-backend store))
        (name (session-store-collection store)))
    (let ((rows (db:select name (q:compile-query :all))))
      (mapcar #'%row-to-session rows))))

(defmethod fluxion.server:gc-sessions ((store db-session-store) ttl)
  (let* ((db:*backend* (session-store-backend store))
         (name (session-store-collection store))
         (cutoff (- (get-universal-time) ttl))
         (expired (db:select name (q:compile-query `(:< last_accessed_at ,cutoff)))))
    (when expired
      (db:remove name (q:compile-query `(:< last_accessed_at ,cutoff))))
    (length expired)))

;;; -------------------------------------------------------
;;; App integration
;;; -------------------------------------------------------

(defun restore-sessions (app)
  "Load persisted sessions into the app's in-memory session table.
Call this after server start to restore sessions from the previous run.
Per-session components are recreated from factories."
  (let ((store (fluxion.server:app-session-store app))
        (restored 0))
    (dolist (session (fluxion.server:load-all-sessions store))
      ;; Recreate per-session components from factories
      (maphash (lambda (id factory-fn)
                 (let ((c (funcall factory-fn)))
                   (setf (gethash id (fluxion.server:session-components session)) c)
                   (setf (fluxion.components:component-session c) session)
                   (fluxion.components:component-mounted c session)))
               (fluxion.server:app-component-factories app))
      (bordeaux-threads:with-lock-held ((fluxion.server:app-session-lock app))
        (setf (gethash (fluxion.server:session-id session)
                       (fluxion.server:app-sessions app))
              session))
      (incf restored))
    (when (plusp restored)
      (format t "[fluxion] Restored ~D session~:P from store~%" restored))
    restored))

(defun persist-session (app session)
  "Write a single session to the app's session store."
  (fluxion.server:store-session (fluxion.server:app-session-store app) session))
